spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8888}

db:
  url: jdbc:h2:~/gsxask
  username: gwt
  password: gwt
  driver: org.h2.Driver